const List<Map<String, dynamic>> countryPhoneCodes = <Map<String, dynamic>>[
  {
    'country': 'Uzbekistan',
    'countryRU': 'Узбекистан',
    'internalPhoneCode': '998',
    'countryCode': 'UZ',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Russia',
    'countryRU': 'Россия',
    'internalPhoneCode': '7',
    'countryCode': 'RU',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Tajikistan',
    'countryRU': 'Таджикистан',
    'internalPhoneCode': '992',
    'countryCode': 'TJ',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Kazakhstan',
    'countryRU': 'Казахстан',
    'internalPhoneCode': '7',
    'countryCode': 'KZ',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Kyrgyzstan',
    'countryRU': 'Кыргызстан',
    'internalPhoneCode': '996',
    'countryCode': 'KG',
    'phoneMask': '### ######',
  },
  {
    'country': 'Georgia',
    'countryRU': 'Грузия',
    'internalPhoneCode': '995',
    'countryCode': 'GE',
    'phoneMask': '### ######',
  },
  {
    'country': 'Germany',
    'countryRU': 'Германия',
    'internalPhoneCode': '49',
    'countryCode': 'DE',
    'phoneMask': '## #########',
  },
  {
    'country': 'Thailand',
    'countryRU': 'Тайланд',
    'internalPhoneCode': '66',
    'countryCode': 'TH',
    'phoneMask': '# ### ## ##',
  },
  {
    'country': 'Afghanistan',
    'countryRU': 'Афганистан',
    'internalPhoneCode': '93',
    'countryCode': 'AF',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Albania',
    'countryRU': 'Албания',
    'internalPhoneCode': '355',
    'countryCode': 'AL',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Algeria',
    'countryRU': 'Алжир',
    'internalPhoneCode': '213',
    'countryCode': 'DZ',
    'phoneMask': '# ### ## ##',
  },
  {
    'country': 'American Samoa',
    'countryRU': 'Американское Самоа',
    'internalPhoneCode': '1684',
    'countryCode': 'AS',
    'phoneMask': '### ## ##',
  },
  {
    'country': 'Andorra',
    'countryRU': 'Андорра',
    'internalPhoneCode': '376',
    'countryCode': 'AD',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Angola',
    'countryRU': 'Ангола',
    'internalPhoneCode': '244',
    'countryCode': 'AO',
    'phoneMask': '#### ### ## ##',
  },
  {
    'country': 'Argentina',
    'countryRU': 'Аргентина',
    'internalPhoneCode': '54',
    'countryCode': 'AR',
    'phoneMask': '# ### ## ##',
  },
  {
    'country': 'Armenia',
    'countryRU': 'Армения',
    'internalPhoneCode': '374',
    'countryCode': 'AM',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Aruba',
    'countryRU': 'Аруба',
    'internalPhoneCode': '297',
    'countryCode': 'AW',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Australia',
    'countryRU': 'Австралия',
    'internalPhoneCode': '61',
    'countryCode': 'AU',
    'phoneMask': '#### ## ##',
    'altMasks': [
      '# #### ## ##',
    ],
  },
  {
    'country': 'Austria',
    'countryRU': 'Австрия',
    'internalPhoneCode': '43',
    'countryCode': 'AT',
    'phoneMask': '### #### ## ##',
  },
  {
    'country': 'Azerbaijan',
    'countryRU': 'Азербайджан',
    'internalPhoneCode': '994',
    'countryCode': 'AZ',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Bahrain',
    'countryRU': 'Бахрейн',
    'internalPhoneCode': '973',
    'countryCode': 'BH',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Bangladesh',
    'countryRU': 'Бангладеш',
    'internalPhoneCode': '880',
    'countryCode': 'BD',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Barbados',
    'countryRU': 'Барбадос',
    'internalPhoneCode': '1246',
    'countryCode': 'BB',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Belarus',
    'countryRU': 'Беларусь',
    'internalPhoneCode': '375',
    'countryCode': 'BY',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Belgium',
    'countryRU': 'Бельгия',
    'internalPhoneCode': '32',
    'countryCode': 'BE',
    'phoneMask': '### ## ## ##',
  },
  {
    'country': 'Bermuda',
    'countryRU': 'Бермуды',
    'internalPhoneCode': '1441',
    'countryCode': 'BM',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Bhutan',
    'countryRU': 'Бутан',
    'internalPhoneCode': '975',
    'countryCode': 'BT',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Brazil',
    'countryRU': 'Бразилия',
    'internalPhoneCode': '55',
    'countryCode': 'BR',
    'phoneMask': '## #### ####',
    'altMasks': [
      '## ## ##### ####',
    ],
  },
  {
    'country': 'Bulgaria',
    'countryRU': 'Болгария',
    'internalPhoneCode': '359',
    'countryCode': 'BG',
    'phoneMask': '# ### ## ##',
  },
  {
    'country': 'Burkina Faso',
    'countryRU': 'Буркина Фасо',
    'internalPhoneCode': '226',
    'countryCode': 'BF',
    'phoneMask': '### # ### ## ##',
  },
  {
    'country': 'Burundi',
    'countryRU': 'Бурунди',
    'internalPhoneCode': '257',
    'countryCode': 'BI',
    'phoneMask': '### ## ##',
  },
  {
    'country': 'Cambodia',
    'countryRU': 'Камбоджа',
    'internalPhoneCode': '855',
    'countryCode': 'KH',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Cameroon',
    'countryRU': 'Камерун',
    'internalPhoneCode': '237',
    'countryCode': 'CM',
    'phoneMask': '# ### ## ##',
  },
  {
    'country': 'United States',
    'countryRU': 'США',
    'internalPhoneCode': '1',
    'countryCode': 'US',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Canada',
    'countryRU': 'Канада',
    'internalPhoneCode': '1',
    'countryCode': 'CA',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Central African Republic',
    'countryRU': 'Центральноафриканская Республика',
    'internalPhoneCode': '236',
    'countryCode': 'CF',
    'phoneMask': '# ### ## ##',
  },
  {
    'country': 'Chad',
    'countryRU': 'Чад',
    'internalPhoneCode': '235',
    'countryCode': 'TD',
    'phoneMask': '# ### ## ##',
  },
  {
    'country': 'Chile',
    'countryRU': 'Чили',
    'internalPhoneCode': '56',
    'countryCode': 'CL',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'China',
    'countryRU': 'Китай',
    'internalPhoneCode': '86',
    'countryCode': 'CN',
    'phoneMask': '### #### ## ##',
  },
  {
    'country': 'Christmas Island',
    'countryRU': 'Остров Рождества',
    'internalPhoneCode': '61',
    'countryCode': 'CX',
    'phoneMask': '# #### ## ##',
  },
  {
    'country': 'Colombia',
    'countryRU': 'Колумбия',
    'internalPhoneCode': '57',
    'countryCode': 'CO',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Comoros',
    'countryRU': 'Коморские острова',
    'internalPhoneCode': '269',
    'countryCode': 'KM',
    'phoneMask': '### ## ##',
  },
  {
    'country': 'Congo',
    'countryRU': 'Конго',
    'internalPhoneCode': '242',
    'countryCode': 'CG',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Cook Islands',
    'countryRU': 'Острова Кука',
    'internalPhoneCode': '682',
    'countryCode': 'CK',
    'phoneMask': '## ###',
  },
  {
    'country': 'Costa Rica',
    'countryRU': 'Коста Рика',
    'internalPhoneCode': '506',
    'countryCode': 'CR',
    'phoneMask': '# ### ## ##',
  },
  {
    'country': 'Croatia',
    'countryRU': 'Хорватия',
    'internalPhoneCode': '385',
    'countryCode': 'HR',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Cuba',
    'countryRU': 'Куба',
    'internalPhoneCode': '53',
    'countryCode': 'CU',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Cyprus',
    'countryRU': 'Кипр',
    'internalPhoneCode': '357',
    'countryCode': 'CY',
    'phoneMask': '# ### ## ##',
  },
  {
    'country': 'Czech Republic',
    'countryRU': 'Чешская Республика',
    'internalPhoneCode': '420',
    'countryCode': 'CZ',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Denmark',
    'countryRU': 'Дания',
    'internalPhoneCode': '45',
    'countryCode': 'DK',
    'phoneMask': '# ### ## ##',
  },
  {
    'country': 'Djibouti',
    'countryRU': 'Джибути',
    'internalPhoneCode': '253',
    'countryCode': 'DJ',
    'phoneMask': '# ### ## ##',
  },
  {
    'country': 'Dominica',
    'countryRU': 'Доминика',
    'internalPhoneCode': '1767',
    'countryCode': 'DM',
    'phoneMask': '### ## ##',
  },
  {
    'country': 'Dominican Republic',
    'countryRU': 'Доминиканская Республика',
    'internalPhoneCode': '1809',
    'countryCode': 'DO',
    'phoneMask': '### ## ##',
  },
  {
    'country': 'Ecuador',
    'countryRU': 'Эквадор',
    'internalPhoneCode': '593',
    'countryCode': 'EC',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Egypt',
    'countryRU': 'Египет',
    'internalPhoneCode': '20',
    'countryCode': 'EG',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'El Salvador',
    'countryRU': 'Сальвадор',
    'internalPhoneCode': '503',
    'countryCode': 'SV',
    'phoneMask': '## #### ## ##',
  },
  {
    'country': 'Equatorial Guinea',
    'countryRU': 'Экваториальная Гвинея',
    'internalPhoneCode': '240',
    'countryCode': 'GQ',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Eritrea',
    'countryRU': 'Эритрея',
    'internalPhoneCode': '291',
    'countryCode': 'ER',
    'phoneMask': '### ## ##',
  },
  {
    'country': 'Estonia',
    'countryRU': 'Эстония',
    'internalPhoneCode': '372',
    'countryCode': 'EE',
    'phoneMask': '### #### ## ##',
    'altMasks': [
      '### ### ## ##',
      '### #### ## ##',
      '### #########',
    ]
  },
  {
    'country': 'Ethiopia',
    'countryRU': 'Эфиопия',
    'internalPhoneCode': '251',
    'countryCode': 'ET',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Faroe Islands',
    'countryRU': 'Фарерские острова',
    'internalPhoneCode': '298',
    'countryCode': 'FO',
    'phoneMask': ' ######',
  },
  {
    'country': 'Fiji',
    'countryRU': 'Фиджи',
    'internalPhoneCode': '679',
    'countryCode': 'FJ',
    'phoneMask': ' ### ## ##',
  },
  {
    'country': 'Finland',
    'countryRU': 'Финляндия',
    'internalPhoneCode': '358',
    'countryCode': 'FI',
    'phoneMask': ' ## ### ## ##',
  },
  {
    'country': 'France',
    'countryRU': 'Франция',
    'internalPhoneCode': '33',
    'countryCode': 'FR',
    'phoneMask': '# ## ## ## ##',
  },
  {
    'country': 'French Guiana',
    'countryRU': 'Французская Гвиана',
    'internalPhoneCode': '594',
    'countryCode': 'GF',
    'phoneMask': '### ## ## ##',
  },
  {
    'country': 'French Polynesia',
    'countryRU': 'Французская Полинезия',
    'internalPhoneCode': '689',
    'countryCode': 'PF',
    'phoneMask': '######',
  },
  {
    'country': 'Gabon',
    'countryRU': 'Габон',
    'internalPhoneCode': '241',
    'countryCode': 'GA',
    'phoneMask': '######',
  },
  {
    'country': 'Gambia',
    'countryRU': 'Гамбия',
    'internalPhoneCode': '220',
    'countryCode': 'GM',
    'phoneMask': '### ## ##',
  },
  {
    'country': 'Ghana',
    'countryRU': 'Гана',
    'internalPhoneCode': '233',
    'countryCode': 'GH',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Greece',
    'countryRU': 'Греция',
    'internalPhoneCode': '30',
    'countryCode': 'GR',
    'phoneMask': ' # ### ## ##',
  },
  {
    'country': 'Greenland',
    'countryRU': 'Гренландия',
    'internalPhoneCode': '299',
    'countryCode': 'GL',
    'phoneMask': '######',
  },
  {
    'country': 'Grenada',
    'countryRU': 'Гренада',
    'internalPhoneCode': '1473',
    'countryCode': 'GD',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Guadeloupe',
    'countryRU': 'Гваделупа',
    'internalPhoneCode': '590',
    'countryCode': 'GP',
    'phoneMask': '### ## ## ##',
  },
  {
    'country': 'Guinea',
    'countryRU': 'Гвинея',
    'internalPhoneCode': '224',
    'countryCode': 'GN',
    'phoneMask': '### ######',
  },
  {
    'country': 'Haiti',
    'countryRU': 'Гаити',
    'internalPhoneCode': '509',
    'countryCode': 'HT',
    'phoneMask': '### ## ##',
  },
  {
    'country': 'Honduras',
    'countryRU': 'Гондурас',
    'internalPhoneCode': '504',
    'countryCode': 'HN',
    'phoneMask': '### ## ##',
  },
  {
    'country': 'Hungary',
    'countryRU': 'Венгрия',
    'internalPhoneCode': '36',
    'countryCode': 'HU',
    'phoneMask': '# ### ## ##',
    'altMasks': [
      '## ## ### ## ##',
    ],
  },
  {
    'country': 'Hungary Alternative',
    'countryRU': 'Венгрия альтернатива',
    'internalPhoneCode': '#6',
    'countryCode': 'HU',
    'phoneMask': '# ### ## ##',
    'altMasks': [
      '## ## ### ## ##',
    ],
  },
  {
    'country': 'Iceland',
    'countryRU': 'Исландия',
    'internalPhoneCode': '354',
    'countryCode': 'IS',
    'phoneMask': '### ## ##',
  },
  {
    'country': 'India',
    'countryRU': 'Индия',
    'internalPhoneCode': '91',
    'countryCode': 'IN',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Indonesia',
    'countryRU': 'Индонезия',
    'internalPhoneCode': '62',
    'countryCode': 'ID',
    'phoneMask': '## #### ## ##',
  },
  {
    'country': 'Iraq',
    'countryRU': 'Ирак',
    'internalPhoneCode': '964',
    'countryCode': 'IQ',
    'phoneMask': '## ### #####',
  },
  {
    'country': 'Ireland',
    'countryRU': 'Ирландия',
    'internalPhoneCode': '353',
    'countryCode': 'IE',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Israel',
    'countryRU': 'Израиль',
    'internalPhoneCode': '972',
    'countryCode': 'IL',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Italy',
    'countryRU': 'Италия',
    'internalPhoneCode': '39',
    'countryCode': 'IT',
    'phoneMask': '## #### ####',
  },
  {
    'country': 'Jamaica',
    'countryRU': 'Ямайка',
    'internalPhoneCode': '1876',
    'countryCode': 'JM',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Japan',
    'countryRU': 'Япония',
    'internalPhoneCode': '81',
    'countryCode': 'JP',
    'phoneMask': '## #### ####',
  },
  {
    'country': 'Kenya',
    'countryRU': 'Кения',
    'internalPhoneCode': '254',
    'countryCode': 'KE',
    'phoneMask': '### ######',
  },
  {
    'country': 'Kuwait',
    'countryRU': 'Кувейт',
    'internalPhoneCode': '965',
    'countryCode': 'KW',
    'phoneMask': '#### ## ##',
  },
  {
    'country': 'Latvia',
    'countryRU': 'Латвия',
    'internalPhoneCode': '371',
    'countryCode': 'LV',
    'phoneMask': '#### ## ##',
  },
  {
    'country': 'Lebanon',
    'countryRU': 'Ливан',
    'internalPhoneCode': '961',
    'countryCode': 'LB',
    'phoneMask': '## ### ###',
  },
  {
    'country': 'Lesotho',
    'countryRU': 'Лесото',
    'internalPhoneCode': '266',
    'countryCode': 'LS',
    'phoneMask': '#### ## ##',
  },
  {
    'country': 'Liechtenstein',
    'countryRU': 'Лихтенштейн',
    'internalPhoneCode': '423',
    'countryCode': 'LI',
    'phoneMask': '### ## ##',
  },
  {
    'country': 'Lithuania',
    'countryRU': 'Литва',
    'internalPhoneCode': '370',
    'countryCode': 'LT',
    'phoneMask': '### ## ##',
  },
  {
    'country': 'Luxembourg',
    'countryRU': 'Люксембург',
    'internalPhoneCode': '352',
    'countryCode': 'LU',
    'phoneMask': '######',
  },
  {
    'country': 'Madagascar',
    'countryRU': 'Мадакаскар',
    'internalPhoneCode': '261',
    'countryCode': 'MG',
    'phoneMask': '### ## ##',
  },
  {
    'country': 'Malaysia',
    'countryRU': 'Малазия',
    'internalPhoneCode': '60',
    'countryCode': 'MY',
    'phoneMask': '# #### ## ##',
  },
  {
    'country': 'Maldives',
    'countryRU': 'Мальдивы',
    'internalPhoneCode': '960',
    'countryCode': 'MV',
    'phoneMask': '### ## ##',
  },
  {
    'country': 'Mali',
    'countryRU': 'Мали',
    'internalPhoneCode': '223',
    'countryCode': 'ML',
    'phoneMask': '#### ## ##',
  },
  {
    'country': 'Malta',
    'countryRU': 'Мальта',
    'internalPhoneCode': '356',
    'countryCode': 'MT',
    'phoneMask': '#### ## ##',
  },
  {
    'country': 'Mexico',
    'countryRU': 'Мехико',
    'internalPhoneCode': '52',
    'countryCode': 'MX',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Monaco',
    'countryRU': 'Монако',
    'internalPhoneCode': '377',
    'countryCode': 'MC',
    'phoneMask': '#### ## ##',
  },
  {
    'country': 'Mongolia',
    'countryRU': 'Монголия',
    'internalPhoneCode': '976',
    'countryCode': 'MN',
    'phoneMask': '## ######',
  },
  {
    'country': 'Montenegro',
    'countryRU': 'Черногория',
    'internalPhoneCode': '382',
    'countryCode': 'ME',
    'phoneMask': '## ######',
  },
  {
    'country': 'Morocco',
    'countryRU': 'Марокко',
    'internalPhoneCode': '212',
    'countryCode': 'MA',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Nepal',
    'countryRU': 'Непал',
    'internalPhoneCode': '977',
    'countryCode': 'NP',
    'phoneMask': '### ### ### ## ##',
  },
  {
    'country': 'Netherlands',
    'countryRU': 'Нидерланды',
    'internalPhoneCode': '31',
    'countryCode': 'NL',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'New Zealand',
    'countryRU': 'Новая Зеландия',
    'internalPhoneCode': '64',
    'countryCode': 'NZ',
    'phoneMask': '# ### ## ##',
    'altMasks': [
      '## ## ### ## ##',
      '## ### ### ## ##',
    ],
  },
  {
    'country': 'Nigeria',
    'countryRU': 'Нигерия',
    'internalPhoneCode': '234',
    'countryCode': 'NG',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Norway',
    'countryRU': 'Норвегия',
    'internalPhoneCode': '47',
    'countryCode': 'NO',
    'phoneMask': '#### ## ##',
  },
  {
    'country': 'Oman',
    'countryRU': 'Оман',
    'internalPhoneCode': '968',
    'countryCode': 'OM',
    'phoneMask': '#### ## ##',
  },
  {
    'country': 'Pakistan',
    'countryRU': 'Пакистан',
    'internalPhoneCode': '92',
    'countryCode': 'PK',
    'phoneMask': '### #######',
  },
  {
    'country': 'Palau',
    'countryRU': 'Палау',
    'internalPhoneCode': '680',
    'countryCode': 'PW',
    'phoneMask': ' ### ## ##',
  },
  {
    'country': 'Panama',
    'countryRU': 'Панама',
    'internalPhoneCode': '507',
    'countryCode': 'PA',
    'phoneMask': ' ### ## ##',
  },
  {
    'country': 'Paraguay',
    'countryRU': 'Парагвай',
    'internalPhoneCode': '595',
    'countryCode': 'PY',
    'phoneMask': ' ### ######',
  },
  {
    'country': 'Peru',
    'countryRU': 'Перу',
    'internalPhoneCode': '51',
    'countryCode': 'PE',
    'phoneMask': '## #########',
  },
  {
    'country': 'Philippines',
    'countryRU': 'Филипины',
    'internalPhoneCode': '63',
    'countryCode': 'PH',
    'phoneMask': ' ## ### ## ##',
  },
  {
    'country': 'Poland',
    'countryRU': 'Польша',
    'internalPhoneCode': '48',
    'countryCode': 'PL',
    'phoneMask': ' ## ### ## ##',
  },
  {
    'country': 'Portugal',
    'countryRU': 'Португалия',
    'internalPhoneCode': '351',
    'countryCode': 'PT',
    'phoneMask': '### ### ###',
  },
  {
    'country': 'Puerto Rico',
    'countryRU': 'Пуэрто Рико',
    'internalPhoneCode': '1939',
    'countryCode': 'PR',
    'phoneMask': '### ## ##',
  },
  {
    'country': 'Qatar',
    'countryRU': 'Катар',
    'internalPhoneCode': '974',
    'countryCode': 'QA',
    'phoneMask': '#### ## ##',
  },
  {
    'country': 'Romania',
    'countryRU': 'Румыния',
    'internalPhoneCode': '40',
    'countryCode': 'RO',
    'phoneMask': '### ### ###',
  },
  {
    'country': 'Rwanda',
    'countryRU': 'Руанда',
    'internalPhoneCode': '250',
    'countryCode': 'RW',
    'phoneMask': '### ### ###',
  },
  {
    'country': 'Samoa',
    'countryRU': 'Самоа',
    'internalPhoneCode': '685',
    'countryCode': 'WS',
    'phoneMask': '### ## ##',
  },
  {
    'country': 'San Marino',
    'countryRU': 'Сан Марино',
    'internalPhoneCode': '378',
    'countryCode': 'SM',
    'phoneMask': '### #### ######',
  },
  {
    'country': 'Saudi Arabia',
    'countryRU': 'Саудовская Аравия',
    'internalPhoneCode': '966',
    'countryCode': 'SA',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Senegal',
    'countryRU': 'Сенегал',
    'internalPhoneCode': '221',
    'countryCode': 'SN',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Serbia',
    'countryRU': 'Сербия',
    'internalPhoneCode': '381',
    'countryCode': 'RS',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Seychelles',
    'countryRU': 'Сейшельские острова',
    'internalPhoneCode': '248',
    'countryCode': 'SC',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Sierra Leone',
    'countryRU': 'Сьерра Леоне',
    'internalPhoneCode': '232',
    'countryCode': 'SL',
    'phoneMask': '### ## ######',
  },
  {
    'country': 'Singapore',
    'countryRU': 'Сингапур',
    'internalPhoneCode': '65',
    'countryCode': 'SG',
    'phoneMask': '#### ## ##',
  },
  {
    'country': 'Slovakia',
    'countryRU': 'Словакия',
    'internalPhoneCode': '421',
    'countryCode': 'SK',
    'phoneMask': '### ## ### ## ##',
  },
  {
    'country': 'Slovenia',
    'countryRU': 'Словения',
    'internalPhoneCode': '386',
    'countryCode': 'SI',
    'phoneMask': '# ### ## ##',
  },
  {
    'country': 'Solomon Islands',
    'countryRU': 'Соломоновы острова',
    'internalPhoneCode': '677',
    'countryCode': 'SB',
    'phoneMask': '### #####',
  },
  {
    'country': 'South Africa',
    'countryRU': 'Южная Африка',
    'internalPhoneCode': '27',
    'countryCode': 'ZA',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Spain',
    'countryRU': 'Испания',
    'internalPhoneCode': '34',
    'countryCode': 'ES',
    'phoneMask': '### ### ###',
  },
  {
    'country': 'Sri Lanka',
    'countryRU': 'Шри Ланка',
    'internalPhoneCode': '94',
    'countryCode': 'LK',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Sudan',
    'countryRU': 'Судан',
    'internalPhoneCode': '249',
    'countryCode': 'SD',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Suriname',
    'countryRU': 'Суринам',
    'internalPhoneCode': '597',
    'countryCode': 'SR',
    'phoneMask': '### ######',
  },
  {
    'country': 'Swaziland',
    'countryRU': 'Свазиленд',
    'internalPhoneCode': '268',
    'countryCode': 'SZ',
    'phoneMask': '# ### ## ##',
  },
  {
    'country': 'Sweden',
    'countryRU': 'Швеция',
    'internalPhoneCode': '46',
    'countryCode': 'SE',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Switzerland',
    'countryRU': 'Швейцария',
    'internalPhoneCode': '41',
    'countryCode': 'CH',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Togo',
    'countryRU': 'Того',
    'internalPhoneCode': '228',
    'countryCode': 'TG',
    'phoneMask': '### # ### ## ##',
  },
  {
    'country': 'Tokelau',
    'countryRU': 'Токелау',
    'internalPhoneCode': '690',
    'countryCode': 'TK',
    'phoneMask': '### ## ##',
  },
  {
    'country': 'Tonga',
    'countryRU': 'Тонга',
    'internalPhoneCode': '676',
    'countryCode': 'TO',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Trinidad and Tobago',
    'countryRU': 'Тринидад и Тобаго',
    'internalPhoneCode': '1868',
    'countryCode': 'TT',
    'phoneMask': '# ### ### ## ##',
  },
  {
    'country': 'Tunisia',
    'countryRU': 'Тунис',
    'internalPhoneCode': '216',
    'countryCode': 'TN',
    'phoneMask': '#### ## ##',
  },
  {
    'country': 'Turkey',
    'countryRU': 'Турция',
    'internalPhoneCode': '90',
    'countryCode': 'TR',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Turkmenistan',
    'countryRU': 'Туркменистан',
    'internalPhoneCode': '993',
    'countryCode': 'TM',
    'phoneMask': '## ######',
  },
  {
    'country': 'Turks and Caicos Islands',
    'countryRU': 'Острова Теркс и Кайкос',
    'internalPhoneCode': '1649',
    'countryCode': 'TC',
    'phoneMask': '# ### ### ## ##',
  },
  {
    'country': 'Tuvalu',
    'countryRU': 'Тувалу',
    'internalPhoneCode': '688',
    'countryCode': 'TV',
    'phoneMask': '#####',
  },
  {
    'country': 'Uganda',
    'countryRU': 'Уганда',
    'internalPhoneCode': '256',
    'countryCode': 'UG',
    'phoneMask': '### ######',
  },
  {
    'country': 'Ukraine',
    'countryRU': 'Украина',
    'internalPhoneCode': '380',
    'countryCode': 'UA',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'United Arab Emirates',
    'countryRU': 'Объединенные Арабские Эмираты',
    'internalPhoneCode': '971',
    'countryCode': 'AE',
    'phoneMask': '## #######',
    'altMasks': [
      '### ## #######',
    ],
  },
  {
    'country': 'United Kingdom',
    'countryRU': 'Великобритания',
    'internalPhoneCode': '44',
    'countryCode': 'GB',
    'phoneMask': '#### #### ## ##',
  },
  {
    'country': 'Uruguay',
    'countryRU': 'Уругвай',
    'internalPhoneCode': '598',
    'countryCode': 'UY',
    'phoneMask': '#### ## ##',
  },
  {
    'country': 'Vanuatu',
    'countryRU': 'Вануату',
    'internalPhoneCode': '678',
    'countryCode': 'VU',
    'phoneMask': '#####',
  },
  {
    'country': 'Wallis and Futuna',
    'countryRU': 'Уоллис и Футуна',
    'internalPhoneCode': '681',
    'countryCode': 'WF',
    'phoneMask': '### ## ## ##',
  },
  {
    'country': 'Yemen',
    'countryRU': 'Йемен',
    'internalPhoneCode': '967',
    'countryCode': 'YE',
    'phoneMask': '# ######',
  },
  {
    'country': 'Zambia',
    'countryRU': 'Замбия',
    'internalPhoneCode': '260',
    'countryCode': 'ZM',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Zimbabwe',
    'countryRU': 'Зибваве',
    'internalPhoneCode': '263',
    'countryCode': 'ZW',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Land Islands',
    'countryRU': 'Острова суши',
    'internalPhoneCode': '354',
    'countryCode': 'AX',
    'phoneMask': '### ## ##',
  },
  {
    'country': 'Bolivia, Plurinational State of',
    'countryRU': 'Боливия, Многонациональное Государство',
    'internalPhoneCode': '591',
    'countryCode': 'BO',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Brunei Darussalam',
    'countryRU': 'Бруней Даруссалам',
    'internalPhoneCode': '673',
    'countryCode': 'BN',
    'phoneMask': '### ## ##',
  },
  {
    'country': 'Cocos Keeling Islands',
    'countryRU': 'Кокосовые Килинг острова',
    'internalPhoneCode': '61',
    'countryCode': 'CC',
    'phoneMask': '# #### ## ##',
  },
  {
    'country': 'Congo, The Democratic Republic of the',
    'countryRU': 'Конго, Демократическая Республика',
    'internalPhoneCode': '243',
    'countryCode': 'CD',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Cote d\'Ivoire',
    'countryRU': 'Кот д\'Ивуара',
    'internalPhoneCode': '225',
    'countryCode': 'CI',
    'phoneMask': '########',
  },
  {
    'country': 'Falkland Islands Malvinas',
    'countryRU': 'Фолклендские Мальвинские острова',
    'internalPhoneCode': '500',
    'countryCode': 'FK',
    'phoneMask': '#####',
  },
  {
    'country': 'Hong Kong',
    'countryRU': 'Гонконг',
    'internalPhoneCode': '852',
    'countryCode': 'HK',
    'phoneMask': '#### ## ##',
  },
  {
    'country': 'Iran, Islamic Republic of',
    'countryRU': 'Иран, Исламская Республика',
    'internalPhoneCode': '98',
    'countryCode': 'IR',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Korea ',
    'countryRU': 'Корея ',
    'internalPhoneCode': '850',
    'countryCode': 'KP',
    'phoneMask': '# ### ## ##',
  },
  {
    'country': 'Korea, Republic of',
    'countryRU': 'Корея, Республика',
    'internalPhoneCode': '82',
    'countryCode': 'KR',
    'phoneMask': '## #### ####',
  },
  {
    'country': 'Libyan Arab Jamahiriya',
    'countryRU': 'Ливийская Арабская Джамахирия',
    'internalPhoneCode': '218',
    'countryCode': 'LY',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Macao',
    'countryRU': 'Макао',
    'internalPhoneCode': '853',
    'countryCode': 'MO',
    'phoneMask': '#### ## ##',
  },
  {
    'country': 'Macedonia',
    'countryRU': 'Македония',
    'internalPhoneCode': '389',
    'countryCode': 'MK',
    'phoneMask': '# ### ## ##',
  },
  {
    'country': 'Moldova, Republic of',
    'countryRU': 'Молдова, Республика',
    'internalPhoneCode': '373',
    'countryCode': 'MD',
    'phoneMask': '### #####',
  },
  {
    'country': 'Mozambique',
    'countryRU': 'Мозамбик',
    'internalPhoneCode': '258',
    'countryCode': 'MZ',
    'phoneMask': '### ######',
  },
  {
    'country': 'Palestina',
    'countryRU': 'Палестина',
    'internalPhoneCode': '970',
    'countryCode': 'PS',
    'phoneMask': '# ### ## ##',
  },
  {
    'country': 'Pitcairn',
    'countryRU': 'Питкэрн',
    'internalPhoneCode': '64',
    'countryCode': 'PN',
    'phoneMask': '# ### ## ##',
  },
  {
    'country': 'Saint Barthélemy',
    'countryRU': 'Сен Бартелеми',
    'internalPhoneCode': '590',
    'countryCode': 'BL',
    'phoneMask': '### ## ## ##',
  },
  {
    'country': 'Saint Kitts and Nevis',
    'countryRU': 'Сент Китс и Невис',
    'internalPhoneCode': '1869',
    'countryCode': 'KN',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Saint Lucia',
    'countryRU': 'Сент Люсия',
    'internalPhoneCode': '1758',
    'countryCode': 'LC',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Somalia',
    'countryRU': 'Сомали',
    'internalPhoneCode': '252',
    'countryCode': 'SO',
    'phoneMask': '## ### ###',
  },
  {
    'country': 'Svalbard and Jan Mayen',
    'countryRU': 'Шпицберген и Ян Майен',
    'internalPhoneCode': '47',
    'countryCode': 'SJ',
    'phoneMask': '#### ## ##',
  },
  {
    'country': 'Syrian Arab Republic',
    'countryRU': 'Сирийская Арабская Республика',
    'internalPhoneCode': '963',
    'countryCode': 'SY',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Taiwan',
    'countryRU': 'Тайвань',
    'internalPhoneCode': '886',
    'countryCode': 'TW',
    'phoneMask': '# #### ## ##',
  },
  {
    'country': 'Tanzania',
    'countryRU': 'Танзания',
    'internalPhoneCode': '255',
    'countryCode': 'TZ',
    'phoneMask': '## ### ## ##',
  },
  {
    'country': 'Venezuela, Bolivarian Republic of',
    'countryRU': 'Венесуэла, Боливарианская Республика',
    'internalPhoneCode': '58',
    'countryCode': 'VE',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Viet Nam',
    'countryRU': 'Вьетнам',
    'internalPhoneCode': '84',
    'countryCode': 'VN',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Virgin Islands, British',
    'countryRU': 'Виргинские острова, Британские',
    'internalPhoneCode': '1284',
    'countryCode': 'VG',
    'phoneMask': '### ### ## ##',
  },
  {
    'country': 'Virgin Islands, U.S.',
    'countryRU': 'Виргинские острова, США',
    'internalPhoneCode': '1340',
    'countryCode': 'VI',
    'phoneMask': '### ### ## ##',
  }
];
